// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEMxHgh3GmnzRIjP98r0tet2YVMDgY0VQ',
    appId: '1:913700115830:android:365a66555c36fead1b5657',
    messagingSenderId: '913700115830',
    projectId: 'cherrypick-6',
    databaseURL: 'https://cherrypick-6-default-rtdb.firebaseio.com',
    storageBucket: 'cherrypick-6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_LiiO7DTZD0gVYJp57UPNNhIm2_yAs7c',
    appId: '1:913700115830:ios:4222e235623e28071b5657',
    messagingSenderId: '913700115830',
    projectId: 'cherrypick-6',
    databaseURL: 'https://cherrypick-6-default-rtdb.firebaseio.com',
    storageBucket: 'cherrypick-6.firebasestorage.app',
    iosClientId: '913700115830-e83rk7ffnfg7t1itql7j5hog5b9avio6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cherrypick',
  );
}
